{{- $secretName := printf "%s-nonce-secret" .Chart.Name -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $nonceSecret := "" -}}

{{- if $existingSecret -}}
  {{- $nonceSecret = index $existingSecret.data "nonce-secret" -}}
{{- else -}}
  {{- $nonceSecret = randAlphaNum 64 | b64enc -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  nonce-secret: {{ $nonceSecret | quote }}